---
title: Hackerkid.Github.Io
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Vishnu KS
description: Story of My Life
email: yo@vishnuks.com
author: Vishnu KS
lang: ''
locale: ''
paginate: 10
highlighter: ''
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
plugins: [jekyll-paginate]
paginateLabel: page
paginate_path: page/:num
permalink: "/:categories/:year/:month/:day/:title"
baseurl: /blog
disqusUsername: ''
googleAnalyticsId: UA-105385860-1
bing: ''
yandex: ''
google: ''
sitemap:
  file: "/sitemap.xml"
  exclude:
  - "/404.html"
  include_posts:
  - "/index.html"
  change_frequency_name: daily
  priority_name: '1.00'
